# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20036fdb147e683fab5028fab2285602de4ced2dc6f81ac728f46f53ea1c2f979a52c96ff0962e1573814b3e98c64d69f5a513c95de47473dff3732525f3b127

test:
  secret_key_base: e80fc5f174c7ca473c9d08f5de0821c9e2e15249411186f4fb57275cc0e4c80228685dd77d597be8102cec0df9e954a4d4b34dcb9e9d2657de0893c2c4d83466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
